import { apiSlice } from '@/features/api/apiSlice';
import { LoginInput, RegisterInput } from '@rental/shared';

/**
 * AUTH API SLICE
 * Injects endpoints into the main apiSlice.
 */
export const authApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    login: builder.mutation({
      query: (credentials: LoginInput) => ({
        url: '/auth/login',
        method: 'POST',
        body: credentials,
      }),
    }),
    register: builder.mutation({
      query: (userData: RegisterInput) => ({
        url: '/auth/register',
        method: 'POST',
        body: userData,
      }),
    }),
  }),
});

// Hooks automatically generated by RTK Query
// Naming convention: use + [EndpointName] + Mutation (for POST/PUT) or Query (for GET)
export const { useLoginMutation, useRegisterMutation } = authApiSlice;
