import { apiSlice } from '@/features/api/apiSlice';
import { LoginInput, RegisterInput, IUserPublic } from '@rental/shared';

interface AuthResponse {
  success: boolean;
  message: string;
  data: {
    user: IUserPublic;
  };
}

/**
 * AUTH API SLICE
 * Injects endpoints into the main apiSlice.
 * Tokens are managed via HttpOnly cookies — no token in request/response body.
 */
export const authApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    login: builder.mutation<AuthResponse, LoginInput>({
      query: (credentials) => ({
        url: '/auth/login',
        method: 'POST',
        body: credentials,
      }),
    }),
    register: builder.mutation<AuthResponse, RegisterInput>({
      query: (userData) => ({
        url: '/auth/register',
        method: 'POST',
        body: userData,
      }),
    }),
    logout: builder.mutation<void, void>({
      query: () => ({
        url: '/auth/logout',
        method: 'POST',
      }),
    }),
    getMe: builder.query<AuthResponse, void>({
      query: () => '/auth/me',
    }),
  }),
});

// Hooks automatically generated by RTK Query
export const { useLoginMutation, useRegisterMutation, useLogoutMutation, useGetMeQuery } = authApiSlice;
